# Main application configuration file for review-service.
# Configures server, data source, JPA, Eureka, Resilience4J, Endpoints and SpringDoc settings.
server:
    port: 8089

spring:
    application:
        name: Review-Service
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ReviewDB?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
    boot:
        admin:
            client:
                url: http://localhost:8761/admin
                enabled: true
                instance:
                    service-url: http://localhost:8089
    cloud:
        openfeign:
            circuitbreaker:
                enabled: true

resilience4j:
    circuitbreaker:
        configs:
            default:
                registerHealthIndicator: true
        instances:
            HttpBinClient_getBinWithDelayInSeconds_int:
                minimumNumberOfCalls: 10
                failureRateThreshold: 50
    timelimiter:
        configs:
            default:
                timeoutDuration: 20s

eureka:
    instance:
        hostname: ${vcap.application.uris[0]:localhost}
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
        leaseRenewalIntervalInSeconds: 5
    client:
        region: default
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

management:
    info:
        env:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"

info:
    app:
        name: Review and Rating Module Rest API
        version: 1.0.0
        description: Review and Rating Module Rest API
